import fs from 'fs';

const path = 'C:/MyProject/Seabattle/src/scenes/MenuScene.js';
let src = fs.readFileSync(path, 'utf8');
const start = src.indexOf('  buildOpticsPanel() {');
const end = src.indexOf('  buySight(sight) {');
if (start < 0 || end < 0) throw new Error('markers not found ' + start + ' ' + end);

const next = [
  "  buildOpticsPanel() {",
  "    this.panel.add(",
  "      this.add",
  "        .text(W / 2, 48, t(this.player, 'optics'), {",
  "          fontFamily: 'Georgia, serif',",
  "          fontSize: '26px',",
  "          color: '#e8f4ff',",
  "          fontStyle: '700',",
  "        })",
  "        .setOrigin(0.5),",
  "    );",
  "    this.panel.add(",
  "      this.add",
  "        .text(W / 2, 78, t(this.player, 'opticsHint'), {",
  "          fontFamily: 'Segoe UI, system-ui, sans-serif',",
  "          fontSize: '13px',",
  "          color: '#8ab0c8',",
  "        })",
  "        .setOrigin(0.5),",
  "    );",
  "",
  "    this.opticsSelected = this.opticsSelected || this.player.equippedSight;",
  "    const selected = SIGHTS.find((s) => s.id === this.opticsSelected) || SIGHTS[0];",
  "    const ownedSel = this.player.ownedSights.includes(selected.id);",
  "    const equippedSel = this.player.equippedSight === selected.id;",
  "",
  "    const px = 200;",
  "    const previewTop = 110;",
  "    const previewH = 230;",
  "    const previewCy = previewTop + previewH / 2;",
  "    this.panel.add(",
  "      this.add.rectangle(px, previewCy, 280, previewH, 0x08141c, 1).setStrokeStyle(2, 0x4a8ab0),",
  "    );",
  "    if (this.textures.exists(selected.texture)) {",
  "      const preview = this.add.image(px, previewCy, selected.texture);",
  "      preview.setDisplaySize(200, 200);",
  "      this.panel.add(preview);",
  "    }",
  "",
  "    this.panel.add(",
  "      this.add",
  "        .text(px, previewTop + previewH + 22, sightName(this.player, selected), {",
  "          fontFamily: 'Segoe UI, system-ui, sans-serif',",
  "          fontSize: '20px',",
  "          color: '#ffffff',",
  "          fontStyle: '700',",
  "        })",
  "        .setOrigin(0.5),",
  "    );",
  "",
  "    const btnY = previewTop + previewH + 62;",
  "    if (equippedSel) {",
  "      this.panel.add(this.add.rectangle(px, btnY, 200, 48, 0x1a4030, 1).setStrokeStyle(2, 0x5ad0a0));",
  "      this.panel.add(",
  "        this.add",
  "          .text(px, btnY, t(this.player, 'equipped'), {",
  "            fontFamily: 'Segoe UI, system-ui, sans-serif',",
  "            fontSize: '18px',",
  "            color: '#a8ffc8',",
  "            fontStyle: '700',",
  "          })",
  "          .setOrigin(0.5),",
  "      );",
  "    } else if (ownedSel) {",
  "      this.addPanelHitButton(px, btnY, t(this.player, 'equip'), () => this.equipSight(selected), 200, 48, 0x2a6a4a);",
  "    } else {",
  "      const buyBg = this.add",
  "        .rectangle(px, btnY, 220, 52, 0xc4891a, 1)",
  "        .setStrokeStyle(2, 0xffd27a)",
  "        .setInteractive({ useHandCursor: true });",
  "      const aIcon = this.add.image(px - 70, btnY, 'icon-anchor');",
  "      aIcon.setDisplaySize(28, 28);",
  "      const buyTxt = this.add",
  "        .text(px + 12, btnY, `${t(this.player, 'buy')}  ${selected.price}`, {",
  "          fontFamily: 'Segoe UI, system-ui, sans-serif',",
  "          fontSize: '18px',",
  "          color: '#ffffff',",
  "          fontStyle: '700',",
  "        })",
  "        .setOrigin(0.5);",
  "      buyBg.on('pointerover', () => {",
  "        buyBg.setFillStyle(0xdba028, 1);",
  "        this.input.setDefaultCursor('pointer');",
  "      });",
  "      buyBg.on('pointerout', () => {",
  "        buyBg.setFillStyle(0xc4891a, 1);",
  "        this.input.setDefaultCursor('default');",
  "      });",
  "      buyBg.on('pointerdown', (pointer, _x, _y, event) => {",
  "        event?.stopPropagation?.();",
  "        this.buySight(selected);",
  "      });",
  "      this.panel.add(buyBg);",
  "      this.panel.add(aIcon);",
  "      this.panel.add(buyTxt);",
  "    }",
  "",
  "    SIGHTS.forEach((sight, i) => {",
  "      const y = 120 + i * 68;",
  "      const owned = this.player.ownedSights.includes(sight.id);",
  "      const equipped = this.player.equippedSight === sight.id;",
  "      const isSel = sight.id === this.opticsSelected;",
  "",
  "      const row = this.add",
  "        .rectangle(640, y, 460, 60, isSel ? 0x1a4030 : 0x142838, 0.98)",
  "        .setStrokeStyle(2, equipped ? 0x5ad0a0 : isSel ? 0x7ab0d0 : 0x3a6a88)",
  "        .setInteractive({ useHandCursor: true });",
  "      this.panel.add(row);",
  "",
  "      if (this.textures.exists(sight.texture)) {",
  "        const thumb = this.add.image(440, y, sight.texture);",
  "        thumb.setDisplaySize(48, 48);",
  "        this.panel.add(thumb);",
  "      }",
  "",
  "      this.panel.add(",
  "        this.add",
  "          .text(480, y, sightName(this.player, sight), {",
  "            fontFamily: 'Segoe UI, system-ui, sans-serif',",
  "            fontSize: '18px',",
  "            color: '#e8f4ff',",
  "            fontStyle: '600',",
  "          })",
  "          .setOrigin(0, 0.5),",
  "      );",
  "",
  "      const status = equipped",
  "        ? t(this.player, 'equipped')",
  "        : owned",
  "          ? t(this.player, 'preview')",
  "          : String(sight.price);",
  "      this.panel.add(",
  "        this.add",
  "          .text(850, y, status, {",
  "            fontFamily: 'Segoe UI, system-ui, sans-serif',",
  "            fontSize: '15px',",
  "            color: equipped ? '#a8ffc8' : owned ? '#9ed0ff' : '#ffd27a',",
  "          })",
  "          .setOrigin(1, 0.5),",
  "      );",
  "",
  "      row.on('pointerover', () => this.input.setDefaultCursor('pointer'));",
  "      row.on('pointerout', () => this.input.setDefaultCursor('default'));",
  "      row.on('pointerdown', () => {",
  "        this.opticsSelected = sight.id;",
  "        this.openPanel('optics');",
  "      });",
  "    });",
  "  }",
  "",
  "",
].join('\n');

// Fix the buy text line which needs template literal in output
const fixed = next.replace(
  ".text(px + 12, btnY, `${t(this.player, 'buy')}  ${selected.price}`, {",
  ".text(px + 12, btnY, `${t(this.player, 'buy')}  ${selected.price}`, {",
);

fs.writeFileSync(path, src.slice(0, start) + fixed + src.slice(end));
console.log('optics replaced ok');
